# Generated by Django 3.1.1 on 2020-11-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('tipo_usuario', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuario')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id_usuario'],
            },
        ),
    ]
