# Generated by Django 3.1.1 on 2020-11-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.CharField(blank=True, max_length=11, null=True)),
                ('stock', models.CharField(blank=True, max_length=9, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_producto')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
